-- Copia y pega esto en el "SQL Editor" de tu panel de Supabase

-- 1. Crear la tabla de mensajes
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null
);

-- 2. Habilitar seguridad (RLS)
alter table messages enable row level security;

-- 3. Crear política: Permitir insertar a cualquiera (para el formulario público)
create policy "Cualquiera puede enviar mensajes"
on messages for insert
with check (true);

-- 4. Crear política: Solo acceso lectura con la clave de servicio (Service Role)
-- Por defecto, el cliente anon no puede leer, lo cual es bueno para privacidad.
-- Nuestra API usará la clave secreta o la anon key con políticas específicas si fuera necesario,
-- pero para este caso simple, la inserción pública es lo crítico.
